# Generated by Django 3.1.7 on 2021-04-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Social Worker', max_length=50),
        ),
    ]
