# Generated by Django 3.1.7 on 2021-04-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
