# Generated by Django 3.1.7 on 2021-04-07 03:39

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('portfolio', models.URLField(blank=True, max_length=250)),
                ('image', models.ImageField(upload_to=pages.models.get_people_filepath)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.ImageField(upload_to=pages.models.get_member_filepath),
        ),
    ]
