# Generated by Django 3.1.7 on 2021-04-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
