# Generated by Django 3.1.7 on 2021-04-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post_postsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsocial',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='pages.post'),
        ),
    ]
