export type ProjectListActionType =
  | "FETCH_PROJECT_LIST_INIT"
  | "FETCH_PROJECT_LIST_INPROGRESS"
  | "FETCH_PROJECT_LIST_SUCCESS"
  | "FETCH_PROJECT_LIST_FAILED";

export type ProjectDetailActionType =
  | "FETCH_PROJECT_DETAIL_INIT"
  | "FETCH_PROJECT_DETAIL_INPROGRESS"
  | "FETCH_PROJECT_DETAIL_SUCCESS"
  | "FETCH_PROJECT_DETAIL_FAILED";

export type FundsActionType =
  | "FETCH_FUNDS_INIT"
  | "FETCH_FUNDS_INPROGRESS"
  | "FETCH_FUNDS_SUCCESS"
  | "FETCH_FUNDS_FAILED";
