# Generated by Django 3.1.7 on 2021-04-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedfund',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
